controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
    #interface_name: effort  # Importante: actúa con torques
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      joint1:
        p: 36.0  # Por Zn
        i: 276.0
        d: 1.95
        i_clamp: 15.0
        antiwindup: true
      joint2:
        p: 36.0   # Por ZN
        i: 570.0
        d: 0.95
        i_clamp: 15.0
        antiwindup: true
